### DISCUSSION TITLE
Incorrect module name in a stable ABI wheel?

### DISCUSSION THREAD

**Discussion by stumpylog** [wjakob/nanobind#1076] [Q&A]
I'm transitioning a project to use nanobind, and am seeing an oddity when building via cibuildwheel.  I get a wheel like: "`exifmwg-0.2.0-cp312-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64`", but the compiled .so seems to be specific to Python 3.12: `bindings.cpython-312-x86_64-linux-gnu.so`

I've configured the stable ABI as such:

```cmake
  nanobind_add_module(
    bindings
    NB_STATIC
    NB_SUPPRESS_WARNINGS
    STABLE_ABI
    LTO
    src/exifmwg/bindings.cpp
    ${CORE_SOURCES})
```

as well as 
```toml
[tool.scikit-build]
build-dir = "build/{wheel_tag}"
wheel.py-api = "cp312"
wheel.packages = [ "src/exifmwg" ]
```

Maybe related to #1047
