### DISCUSSION TITLE
stub generation: typing extensions requirement

### DISCUSSION THREAD

**Discussion by jeffective** [wjakob/nanobind#553] [Q&A] [answered]
I have installed nanobind using the git submodule way, but in my CI github actions pipeline I am getting a typing_extensions module not found error. How do I properly use the installation git submodule way so that this typing_extensions dependency is automatically resolved in my build?

**Comment by jeffective** [comment, marked as answer]
the issue resolved itself after i added this to my pyproject.toml (as described in https://nanobind.readthedocs.io/en/latest/packaging.html#step-6-build-wheels-in-the-cloud)

```toml
[tool.cibuildwheel]
# Necessary to see build output from the actual compilation
build-verbosity = 1

# Optional: run pytest to ensure that the package was correctly built
# test-command = "pytest {project}/tests"
# test-requires = "pytest"

# Needed for full C++17 support on macOS
[tool.cibuildwheel.macos.environment]
MACOSX_DEPLOYMENT_TARGET = "10.14"

```
